### ISSUE TITLE
How to use the function in a composition

### ISSUE THREAD

**Issue by passoszup** [upbound/function-cidr#45]
My vpc is being created in this composition but it will get the value through the ipam id. In this case I need to check whether the subnet entries must follow the same cidr and I am using two functions (three in my case). the expample file did not help me understand my problem. How to use the function to take the cird that the vcn received from ipam and distribute the ranges among my subnets of created types. I'm confused

````
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: network.aws.foundation.com
  labels:
    aws.foundation.com/provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.foundation.com/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: common-fields
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.accountID
                toFieldPath: spec.providerConfigRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "aws-provider-config-%s"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
        resources:
          # Create VPC with specified CIDR
          - name: VPN-NETWORK
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: VPC
              spec:
                forProvider:
                  enableDnsSupport: true
                  enableDnsHostnames: true
            patches:
              - type: PatchSet
                patchSetName: common-fields
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ipamPoolId
                toFieldPath: spec.forProvider.ipv4IpamPoolId
              - type: FromCompositeFieldPath
                fromFieldPath: spec.NetmaskLength
                toFieldPath: spec.forProvider.ipv4NetmaskLength
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.vpcId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.cidrBlock
                toFieldPath: status.vpcCidr  # vpc ipam
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.tags
                toFieldPath: spec.forProvider.tags
```
         
          ```
# Conditional VPCIPv4CidrBlockAssociation for additional CIDR
          - name: vpc-ipv4-cidr-association
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: VPCIPv4CidrBlockAssociation
              spec:
                forProvider:
                  cidrBlock: "10.144.0.0/16"
            patches:
              - type: PatchSet
                patchSetName: common-fields
              - type: FromCompositeFieldPath
                fromFieldPath: "status.vpcId"
                toFieldPath: "spec.forProvider.vpcId"
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.cidrBlockAssociationId
                toFieldPath: status.cidrAssociationId

################ INTERNET GATEWAY ###############################
          # Internet Gateways for Subnet public
          - name: Internet-Gateway
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: InternetGateway
              spec:
                forProvider:
                  tags:
                    Name: Internet-Gateway
            patches:
              - type: PatchSet
                patchSetName: common-fields
              - type: FromCompositeFieldPath
                fromFieldPath: "status.vpcId"
                toFieldPath: "spec.forProvider.vpcId"
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.internetGatewayId

############## SUBNET PUBLIC'S ########################
          # Create Public Subnet 1A
          - name: Public-Subnet-1A 
            base: 
              apiVersion: aws.foundation.com/v1alpha1
              kind: XSubnet
              spec:
                subnetType: public
                availabilityZone: "sa-east-1a"
                tags:
                    Name: Public-Subnet-1A
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.resourceConfig.region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.accountID
                toFieldPath: spec.resourceConfig.accountID
              - type: FromCompositeFieldPath
                fromFieldPath: status.internetGatewayId
                toFieldPath: spec.destination.gatewayId
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.irouteTableId
                toFieldPath: status.routeTableIdpublic1a
              - type: FromCompositeFieldPath
                fromFieldPath: status.vpcId
                toFieldPath: spec.vpcId
              - type: FromCompositeFieldPath
                fromFieldPath: status.atFunction.cidr
                toFieldPath: spec.cidrBlock

    
    - step: cidr-subnets-partitions
      functionRef:
        name: upbound-function-cidr
      input:
        apiVersion: cidr.fn.crossplane.io/v1beta1
        kind: Parameters
        cidrFunc: cidrsubnets
        prefixField: desired.composite.resource.status.vpcCidr  # Block CIDR from vpc
        newBits: [1, 1, 1]  # 3 subnets (/25 cada)
        outputField: status.atFunction.cidr # output in status.partitions`
```
            
     
"Message:               cannot compose resources: pipeline step "cidr-subnets-partitions" returned a fatal result: invalid Function input: parameters: Required value: invalid CIDR prefix address desired.composite.resource.status.vpcCidr"

**Comment by haarchri** [comment]
how i using this function - create one Composition + XRD for CIDR 

like:

Composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcidrs.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: platform.upbound.io/v1alpha1
    kind: XCIDR
  mode: Pipeline
  pipeline:
    - step: cidr
      functionRef:
        name: upbound-function-cidr
      input:
        apiVersion: cidr.fn.crossplane.io/v1beta1
        kind: Parameters
        cidrFunc: spec.parameters.cidrFunc
        prefixField: spec.parameters.cidrBlock
        newBitsField: spec.parameters.newBits
        netNumItemsField: spec.parameters.azs
        hostNumField: spec.parameters.hostNum
        offsetField: spec.parameters.offset
        outputField: spec.parameters.output
```

XRD:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcidrs.platform.upbound.io
spec:
  group: platform.upbound.io
  names:
    kind: XCIDR
    plural: xcidrs
  claimNames:
    kind: CIDR
    plural: cidrs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: CIDR input parameters used to calculate network subnets, hosts, and masks.
                  type: object
                  properties:
                    cidrFunc:
                      type: string
                      description: The function to use for CIDR calculations.
                      enum:
                        - cidrsubnet
                        - cidrsubnets
                        - cidrhost
                        - cidrnetmask
                        - cidrsubnetloop
                    cidrBlock:
                      type: string
                      description: The base CIDR block to be used for subnet calculations.
                    newBits:
                      type: array
                      description: Array of integers representing new bits to add for subnetting.
                      items:
                        type: integer
                    azs:
                      type: array
                      description: List of availability zones where the subnets will be created.
                      items:
                        type: string
                    hostNum:
                      type: integer
                      description: Number of hosts required in each subnet.
                    offset:
                      type: integer
                      description: Offset to be applied when calculating subnets.
                    output:
                      type: string
                      description: Desired format of the output CIDR calculation.
              required:
                - parameters
            status:
              type: object
              properties:
                atFunction:
                  type: object
                  description: Output from the function specified in parameters.
                  properties:
                    cidr:
                      type: object
                      description: CIDR-related information derived from the input parameters.
                      properties:
                        host:
                          type: string
                          description: Host address derived from the CIDR calculation.
                        netmask:
                          type: string
                          description: Netmask derived from the CIDR calculation.
                        subnet:
                          type: string
                          description: Subnet address derived from the CIDR calculation.
                        subnets:
                          type: array
                          description: List of subnet addresses derived from the CIDR calculation.
                          items:
                            type: string
```


and then simply use the XR from this in your composition:
this example is in go-template:


```
            ---
            apiVersion: platform.upbound.io/v1alpha1
            kind: XCIDR
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: xcidr
            spec:
              parameters:
                cidrFunc: cidrsubnetloop
                cidrBlock: {{ dig "resources" "vpc" "resource" "status" "atProvider" "cidrBlock" "" $.observed }}
                newBits:
                  - 8
                azs:
                  - {{ printf "%sa" .observed.composite.resource.spec.vpcParameters.region }}
                  - {{ printf "%sb" .observed.composite.resource.spec.vpcParameters.region }}
                  - {{ printf "%sc" .observed.composite.resource.spec.vpcParameters.region }}
                offset: 48
            {{- end }}
            ---
```
